### ISSUE TITLE
Sync PBS Passport status and show availability.

### ISSUE THREAD

**Issue by robinsm** [pbs/pbs-media-manager-craft-plugin#10]
Can the following 3 fields be synced by the media manager.

<img width="1445" alt="Cursor" src="https://user-images.githubusercontent.com/4096355/234786638-7ddbabfb-d0ff-499b-a24b-bb9a74ca9fa0.png">

The video below gives more context on the original discussion.

https://user-images.githubusercontent.com/4096355/234786469-865e58ac-ab93-4bd3-ab62-cfae92174567.mp4

Full length video [here](https://drive.google.com/drive/u/3/folders/1nuXXTIFETjCVYrPWRBsPlPAZi3F6wxXz)

**Comment by andrewmenich** [comment]
@SamLaneyPBS Hi Sam, I'm following up here regarding how a show's 'Passport' status is determined ([question originally asked here](https://github.com/pbs/pbs-media-manager-craft-plugin/issues/8#issuecomment-1789444536))

The 'availabilities' attribute is only on API requests to `/assets/` endpoints rather than the `/shows/<show-id>/` endpoint. How do we know what asset should determine a show's FVOD or MVOD status?

**Comment by SamLaneyPBS** [comment]
Oof. I'm sorry I neglected to talk about this. 

We will have to approximate a show's passport status by looking at the episodes in Season 1. If **any** episode in season 1 is available to passport members, then we can say the show is in Passport. If any episode within Season 1 is available to the Public, then we can also say it is "available to everyone".

**Comment by andrewmenich** [comment]
This logic has been added in [KB v3.3.3](https://github.com/pbs/pbs-media-manager-craft-kenburns/releases/tag/v3.3.3) and is on the KB Develop site for review.

**Comment by SamLaneyPBS** [comment]
When I tried to test this, it started a massive amount of jobs for the CMS. I didn't see the data get updated in the first few minutes of these tasks getting done. Also, the amount of jobs grew considerably as time went on (started at 2k, went up to 6k)

![image](https://github.com/pbs/pbs-media-manager-craft-plugin/assets/129447081/d5e566d7-4429-4f7f-ad34-4679bc85e735)

**Comment by andrewmenich** [comment]
@SamLaneyPBS Since we're interfacing with more fields, this is to be expected. I think syncs will take some time, but the "Updating search indexes" jobs usually process very quickly and do not affect what's in the Show/Media entries, meaning the updated data should already be there for the front end.

**Comment by SamLaneyPBS** [comment]
Gotcha. I just did an all shows sync and tested US and the Holocaust. I had set the show to "available for all" (which is incorrect), and turned off "available in Passport" and "available for purchase". After the sync, "Available in Passport" switched to on (which means it worked and moved to the correct state), however "available for all" did not turn to 'off', and "available for purchase" did not turn to 'on'.

**Comment by smaylath** [comment]
@andrewmenich tagging you to check this out!

**Comment by andrewmenich** [comment]
@SamLaneyPBS The "Available for Purchase" field should be fixed now. "Available for all" is currently determined by looking at each episode's `public` availability and if any are available, then it should be marked as available to public. For Ben Franklin, both episodes have a public availability end date of `2022-04-26`, so it's considering this as not available to the public.

**Comment by SamLaneyPBS** [comment]
hey Andrew, - looks like "available for purchase is working great. I tried once more testing US&H (https://develop-kenburns.console.pbs.org/admin/entries/show/212201-the-u-s-and-the-holocaust?site=default#tab--local), but it looks like the "available for everyone" still isn't working quite right. Strangely, checking other titles for the Passport toggle, such as Muhammad Ali (https://develop-kenburns.console.pbs.org/admin/entries/show/212179-muhammad-ali?site=default) and Ben Franklin (https://develop-kenburns.console.pbs.org/admin/entries/show/212186-benjamin-franklin?site=default#tab--local), both of those are not showing the passport toggle as "on" despite both shows being only available in Passport.

**Comment by andrewmenich** [comment]
@SamLaneyPBS Okay, I believe I've got to the bottom of this now (fingers crossed.) Please try again and let me know if the correct results populate now.

**Comment by SamLaneyPBS** [comment]
Unfortunately, looks like the "available for everyone" toggle is still having trouble. it's incorrect on these shows that I checked:
https://develop-kenburns.console.pbs.org/admin/entries/show/212179-muhammad-ali?site=default#tab--local
https://develop-kenburns.console.pbs.org/admin/entries/show/212201-the-u-s-and-the-holocaust?site=default#tab--local
https://develop-kenburns.console.pbs.org/admin/entries/show/255206-the-american-buffalo?site=default#tab--local

**Comment by andrewmenich** [comment]
@SamLaneyPBS Apologies for all the back and forth on this. The logic that was determining public availability was taking into account things like trailers/clips/previews, so I've changed it to only look at full episodes, which I think should have fixed the issue.

**Comment by smaylath** [comment]
@SamLaneyPBS friendly reminder on this one - if this is approved we have a batch we can ship to preprod

**Comment by SamLaneyPBS** [comment]
Looks like it's working!

**Comment by smaylath** [comment]
deployed to preprod & prod & completed 12.14.23
